### ISSUE TITLE
about training code

### ISSUE THREAD

**Issue by felix-ky** [chroneus/stylematte#1]
Hi, great to see the wonderful work
may i ask that is there any plan to release the training code?

**Comment by chroneus** [comment]
Thanks for your interest!  Right now we are in long stage of peer reviewing and copyright clearance from previous employer.
If you are in hurry to reproduce results, you may modify [vision-aided-gan](https://github.com/nupurkmr9/vision-aided-gan)  (RGB->RGBA)repo for StyleGAN training and [robust video matting](https://github.com/PeterL1n/RobustVideoMatting)(BTCHW->BCHW) for initial source of StyleMatte training.
