### ISSUE TITLE
how to achieve the same results as  huggingface demo

### ISSUE THREAD

**Issue by wtjgh** [chroneus/stylematte#2]
Hello, I am using test.py along with stylematte_pure.pth to test the matting results. However, the results are not as good as those demonstrated on huggingface. Could you please advise me on how to achieve the same results as yours?

**Comment by chroneus** [comment]
stylematte_synth.pth is little better, as we discussed in the article.  
The size of input image could reflect on quality. 
For a post-processing  you may use some functions from pymatting

**Comment by wtjgh** [comment]
Thank you, I will follow your advice and try accordingly.
